#ifndef DEFINES_H
#define DEFINES_H

#define LEVEL_WIDTH 100
#define LEVEL_HEIGHT 100
#define LEVEL_ATLAS_SCALE 1.0f
#define ENTITY_STORE_COUNT 1024
#define QUEUE_MAX_PROCESSED_PER_FRAME 128
#define DRAW_ENTITY_DEBUG 1
#define ENTITY_BASE_ROTATION_SPEED 720.0f
#define ENTITY_BASE_SPEED 10.0f
#define QUICK_TURN_AROUND_MAX 120.0f
#define COMBAT_ROUND_DURATION 2.0f
#define FLOATERS_MAX 16
#define NAVIGATION_MAX_OPEN_SET 1024
#define LEVEL_MESH_ARENA_SIZE Megabytes(2)
#define LEVEL_MESH_MAX_VERTS 16384
#define LEVEL_MESH_MAX_EDGES 16384
#define ENTITY_NAME_CHARS 128
#define VIEWED_ENTITY_MAX 32
#define PLAYER_GOD_MODE true

#endif
