#ifndef SETTINGS_H
#define SETTINGS_H

#define LEVEL_WIDTH 100
#define LEVEL_HEIGHT 100
#define LEVEL_ATLAS_SCALE 0.5f
#define ENTITY_STORE_COUNT 1024
#define QUEUE_MAX_PROCESSED_PER_FRAME 128

#endif