#ifndef SETTINGS_H
#define SETTINGS_H

#define LEVEL_WIDTH 100
#define LEVEL_HEIGHT 100
#define LEVEL_ATLAS_SCALE 0.5f
#define ENTITY_STORE_COUNT 1024
#define QUEUE_MAX_PROCESSED_PER_FRAME 128
#define DRAW_ENTITY_DEBUG 1
#define ENTITY_BASE_ROTATION_SPEED 720.0f
#define ENTITY_BASE_SPEED 10.0f
#define QUICK_TURN_AROUND_MAX 120.0f

#endif